config/routes.rb
Rails.application.routes.draw do

  namespace :mercury do
    resources :images
  end

  mount Mercury::Engine => '/'

  get "/robots.txt" => RobotsGenerator

  get "/sitemap.xml.gz"                        => "sitemap#sitemap", format: :xml
  get "/sitemap/:sitemap_host/generate.xml.gz" => "sitemap#generate", format: :xml, :constraints => { sitemap_host: /[.\-\w]+/ }

  get "/:dv_file" => "domain_validation#index", constraints: {dv_file: /.*\.txt/}

  get "/design" => "design#design"

  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

  post '/webhooks/paypal_ipn' => 'paypal_ipn#ipn_hook', as: :paypal_ipn_hook
  post '/webhooks/plans' => 'plans#create'
  get '/webhooks/trials' => 'plans#get_trials'

  post '/bounces' => 'amazon_bounces#notification'

  get "/people/:person_id/inbox/:id", :to => redirect("/fi/people/%{person_id}/messages/%{id}")
  get "/listings/new/:type" => "listings#new", :as => :new_request_without_locale # needed for some emails, where locale part is already set
  get "/change_locale" => "i18n#change_locale", :as => :change_locale

  namespace :int_api do
    post "/create_trial_marketplace" => "marketplaces#create"
    resources :listings, only: [], defaults: { format: :json } do
      member do
        post :update_working_time_slots
      end
    end
  end

  match '/harmony_proxy/*harmony_path' => 'harmony_proxy#proxy', via: :all

  get "/ui_api/topbar_props" => "topbar_api#props"

  get '/_lp_preview' => 'landing_page#preview'

  locale_regex_string = Sharetribe::AVAILABLE_LOCALES.map { |l| l[:ident] }.concat(Sharetribe::REMOVED_LOCALES.to_a).join("|")
  locale_matcher = Regexp.new(locale_regex_string)
  locale_matcher_anchored = Regexp.new("^(#{locale_regex_string})$")

  get '/:locale/' => 'landing_page#index', as: :landing_page_with_locale, constraints: ->(request) {
    locale_matcher_anchored.match(request.params["locale"]) &&
      CustomLandingPage::LandingPageStore.enabled?(request.env[:current_marketplace]&.id)
  }
  get '/' => 'landing_page#index', as: :landing_page_without_locale, constraints: ->(request) {
    CustomLandingPage::LandingPageStore.enabled?(request.env[:current_marketplace]&.id)
  }

  get '/:locale/s' => 'homepage#index', as: :search_with_locale, constraints: ->(request) {
    locale_matcher_anchored.match(request.params["locale"]) &&
      CustomLandingPage::LandingPageStore.enabled?(request.env[:current_marketplace]&.id)
  }
  get '/s' => 'homepage#index', as: :search_without_locale, constraints: ->(request) {
    CustomLandingPage::LandingPageStore.enabled?(request.env[:current_marketplace]&.id)
  }

  get '/:locale/' => 'homepage#index', :constraints => { :locale => locale_matcher }, as: :homepage_with_locale
  get '/' => 'homepage#index', as: :homepage_without_locale
  get '/:locale/s', to: redirect('/%{locale}', status: 307), constraints: { locale: locale_matcher }
  get '/s', to: redirect('/', status: 307)

  get '/500' => 'errors#server_error'
  get '/404' => 'errors#not_found', :as => :error_not_found
  get '/406' => 'errors#not_acceptable', :as => :error_not_acceptable
  get '/410' => 'errors#gone', as: :error_gone
  get '/community_not_found' => 'errors#community_not_found', as: :community_not_found
  get '/not_available' => 'application#not_available', as: :community_not_available

  resources :communities, only: [:new, :create]

  devise_for :people, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "omniauth" }

  scope "(/:locale)", :constraints => { :locale => locale_matcher } do

    put '/mercury_update' => "mercury_update#update", :as => :mercury_update

    get "/transactions/op_status/:process_token" => "paypal_service/checkout_orders#paypal_op_status", as: :paypal_op_status
    get "/transactions/transaction_op_status/:process_token" => "transactions#transaction_op_status", :as => :transaction_op_status
    get "/transactions/created/:transaction_id" => "transactions#created", as: :transaction_created
    get "/transactions/finalize_processed/:process_token" => "transactions#finalize_processed", as: :transaction_finalize_processed

    get "/transactions/new" => "transactions#new", as: :new_transaction

    get "/listings/:listing_id/book", :to => redirect { |params, request|
      "/#{params[:locale]}/listings/#{params[:listing_id]}/initiate?#{request.query_string}"
    }
    post "/listings/:listing_id/booked"    => "preauthorize_transactions#initiated", as: :booked # POST request, no redirect

    get "/listings/:listing_id/initiate"   => "preauthorize_transactions#initiate", :as => :initiate_order
    post "/listings/:listing_id/initiated" => "preauthorize_transactions#initiated", :as => :initiated_order

    post "/listings/:listing_id/create_contact" => "free_transactions#create_contact", :as => :create_contact
    get "/listings/:listing_id/contact" => "free_transactions#contact", :as => :contact_to_listing

    get "/logout" => "sessions#destroy", :as => :logout
    get "/confirmation_pending" => "community_memberships#confirmation_pending", :as => :confirmation_pending
    get "/login" => "sessions#new", :as => :login
    get "/listing_bubble/:id" => "listings#listing_bubble", :as => :listing_bubble
    get "/listing_bubble_multiple/:ids" => "listings#listing_bubble_multiple", :as => :listing_bubble_multiple
    get '/:person_id/settings/payments' => 'payment_settings#index', :as => :person_payment_settings
    post '/:person_id/settings/payments' => 'payment_settings#create', :as => :create_person_payment_settings
    put '/:person_id/settings/payments' => 'payment_settings#update', :as => :update_person_payment_settings
    get '/:person_id/settings/payments/paypal_account' => 'paypal_accounts#index', :as => :paypal_account_settings_payment

    get  '/community_memberships/pending_consent' => 'community_memberships#pending_consent', as: :pending_consent
    post '/community_memberships/give_consent'    => 'community_memberships#give_consent', as: :give_consent
    get  '/community_memberships/access_denied'   => 'community_memberships#access_denied', as: :access_denied

    get  '/community_memberships/check_email_availability_and_validity' => 'community_memberships#check_email_availability_and_validity'
    get  '/community_memberships/check_invitation_code'                 => 'community_memberships#check_invitation_code'

    namespace :paypal_service do
      resources :checkout_orders do
        collection do
          get :success
          get :cancel
          get :success_processed
        end
      end
    end

    namespace :admin do
      get '' => "getting_started_guide#index"

      resources :payment_preferences, only: [:index], param: :payment_gateway do
        collection do
          put :common_update
          put :update_stripe_keys
        end
        member do
          get :disable
          get :enable
        end
      end
      get  "/paypal_preferences" => redirect("/%{locale}/admin/payment_preferences")
      get  "/paypal_preferences/account_create"       => "paypal_preferences#account_create"
      get  "/paypal_preferences/permissions_verified" => "paypal_preferences#permissions_verified"

      resource :setting, path: 'settings', only: [:show, :update]

      get "getting_started_guide"                        => "getting_started_guide#index",                  as: :getting_started_guide
      get "getting_started_guide/slogan_and_description" => "getting_started_guide#slogan_and_description", as: :getting_started_guide_slogan_and_description
      get "getting_started_guide/cover_photo"            => "getting_started_guide#cover_photo",            as: :getting_started_guide_cover_photo
      get "getting_started_guide/filter"                 => "getting_started_guide#filter",                 as: :getting_started_guide_filter
      get "getting_started_guide/payment"                => "getting_started_guide#payment",                as: :getting_started_guide_payment
      get "getting_started_guide/listing"                => "getting_started_guide#listing",                as: :getting_started_guide_listing
      get "getting_started_guide/invitation"             => "getting_started_guide#invitation",             as: :getting_started_guide_invitation
      get "getting_started_guide/skip_payment"           => "getting_started_guide#skip_payment",           as: :getting_started_guide_skip_payment

      get   "/look_and_feel/edit" => "communities#edit_look_and_feel",          as: :look_and_feel_edit
      patch "/look_and_feel"      => "communities#update_look_and_feel",        as: :look_and_feel
      get   "/details/edit"       => "community_customizations#edit_details",   as: :details_edit
      patch "/details"            => "community_customizations#update_details", as: :details
      get   "/new_layout"         => "communities#new_layout",                  as: :new_layout
      patch "/new_layout"         => "communities#update_new_layout",           as: :update_new_layout

      get   "/topbar/edit"        => "communities/topbar#edit",                 as: :topbar_edit
      patch "/topbar"             => "communities/topbar#update",               as: :topbar

      get   "/footer/edit"        => "communities/footer#edit",                 as: :footer_edit
      patch "/footer"             => "communities/footer#update",               as: :footer

      get   "/landing_page"         => "communities#landing_page",                  as: :landing_page

      resources :communities do
        member do
          get :edit_welcome_email
          post :create_sender_address
          get :check_email_status
          post :resend_verification_email
          get :edit_text_instructions
          get :test_welcome_email
          get :social_media
          get :analytics
          put :social_media, to: 'communities#update_social_media'
          put :analytics, to: 'communities#update_analytics'
          delete :delete_marketplace

app/models/payment_settings.rb
# == Schema Information
#
# Table name: payment_settings
#
#  id                                     :integer          not null, primary key
#  active                                 :boolean          not null
#  community_id                           :integer          not null
#  payment_gateway                        :string(64)
#  payment_process                        :string(64)
#  commission_from_seller                 :integer
#  minimum_price_cents                    :integer
#  minimum_price_currency                 :string(3)
#  minimum_transaction_fee_cents          :integer
#  minimum_transaction_fee_currency       :string(3)
#  confirmation_after_days                :integer          not null
#  created_at                             :datetime         not null
#  updated_at                             :datetime         not null
#  api_client_id                          :string(255)
#  api_private_key                        :string(255)
#  api_publishable_key                    :string(255)
#  api_verified                           :boolean
#  api_visible_private_key                :string(255)
#  api_country                            :string(255)
#  commission_from_buyer                  :integer
#  minimum_buyer_transaction_fee_cents    :integer
#  minimum_buyer_transaction_fee_currency :string(3)
#  key_encryption_padding                 :boolean          default(FALSE)
#
# Indexes
#
#  index_payment_settings_on_community_id  (community_id)
#

class PaymentSettings < ApplicationRecord
  belongs_to :community

  validates_presence_of(:community_id)

  scope :preauthorize, -> { where(payment_process: :preauthorize) }
  scope :paypal, -> { preauthorize.where(payment_gateway: :paypal) }
  scope :stripe, -> { preauthorize.where(payment_gateway: :stripe) }
  scope :active, -> { where(active: true) }

  class << self
    def max_minimum_transaction_fee(community)
      stripe.or(PaymentSettings.paypal)
        .active
        .where(community: community)
        .pluck(:minimum_transaction_fee_cents)
        .compact
        .max
    end
  end
end

app/controllers/payment_settings_controller.rb
class PaymentSettingsController < ApplicationController
  before_action do |controller|
    controller.ensure_logged_in t("layouts.notifications.you_must_log_in_to_view_your_settings")
  end

  before_action :set_service
  before_action :ensure_payments_enabled
  skip_before_action :warn_about_missing_payment_info, only: [:update]

  def index; end

  def create
    unless @presenter.stripe_enabled
      redirect_to action: :index
    end

    @service.create
    flash.now[:error] = @service.stripe_error_message

    warn_about_missing_payment_info
    render 'index'
  end

  def update
    unless (@presenter.stripe_enabled && @presenter.stripe_account_ready)
      redirect_to action: :index
    end

    @service.update
    flash.now[:error] = @service.stripe_error_message

    warn_about_missing_payment_info
    render 'index'
  end

  private

  def set_service
    @selected_left_navi_link = "payments"
    @service = Person::PaymentSettingsService.new(community: @current_community,
                                                  params: params,
                                                  person: @current_user)
    @presenter = Person::PaymentSettingsPresenter.new(service: @service,
                                                      person_url: person_url(@current_user.username))
  end

  def ensure_payments_enabled
    unless @presenter.payments_enabled?
      flash[:warning] = t("stripe_accounts.admin_account_not_connected",
                            contact_admin_link: view_context.link_to(
                              t("stripe_accounts.contact_admin_link_text"),
                                new_user_feedback_path)).html_safe # rubocop:disable Rails/OutputSafety
      redirect_to person_settings_path
    end
  end
end

app/views/payment_settings/_address_fields_form.haml
= fields_for presenter.stripe_account_form do |form|
  = form.hidden_field :token
  .country-dependent{"data-country-except" => "JP"}
    .row
      .col-12
        = form.label :address_line1, t("stripe_accounts.form_new.address_line1")+"*", class: 'required'
        = form.text_field :address_line1, class: 'required'
    .row.country-dependent{"data-country-except" => "IE,HK"}
      .col-12
        = form.label :address_postal_code, t("stripe_accounts.form_new.address_postal_code")+"*"
        = form.text_field :address_postal_code, class: 'required'
    .row
      .col-12
        = form.label :address_city, t("stripe_accounts.form_new.address_city")+"*"
        = form.text_field :address_city, class: 'required'
    .row.country-dependent{"data-country-only" => "AU,IE"}
      .col-12
        = form.label :address_state, t("stripe_accounts.form_new.address_state")+"*"
        = form.text_field :address_state, required: true
    .row.country-dependent{"data-country-only" => "US"}
      .col-12
        = form.label :address_state, t("stripe_accounts.form_new.address_state")+"*"
        = form.select :address_state, us_states.select{|x| x[1] != 'PR'}, { include_blank: true }, required: true
    .row.country-dependent{"data-country-only" => "CA"}
      .col-12
        = form.label :address_state, t("stripe_accounts.form_new.address_province")+"*"
        = form.text_field :address_state, required: true
  .country-dependent{"data-country-only" => "JP"}
    - [:address_kana_postal_code, :address_kana_state, :address_kana_city, :address_kana_town, :address_kana_line1].each do |field|
      .row
        .col-12
          = form.label field, t("stripe_accounts.form_new.#{field}")+"*"
          = form.text_field field, class: 'required'
    - [:address_kanji_postal_code, :address_kanji_state, :address_kanji_city, :address_kanji_town, :address_kanji_line1].each do |field|
      .row
        .col-12
          = form.label field, t("stripe_accounts.form_new.#{field}")+"*"
          = form.text_field field, class: 'required'

  .country-dependent{"data-country-only" => 'US,JP,PR'}
    .row
      .col-12
        = form.label :phone, t("stripe_accounts.form_new.phone_number")+"*"
        = form.text_field :phone, class: 'required'

app/views/payment_settings/_bank_fields_form.haml
- stripe_account_ready = presenter.stripe_account_ready ? true : nil
= fields_for presenter.stripe_bank_form do |form|
  .row.bank-routing-1.hidden
    .col-12
      = form.label :bank_routing_1, t("stripe_accounts.form_bank.bank_routing_1")+"*"
      = form.text_field :bank_routing_1, class: 'required', country_regexp: 'routing_1',
        'stripe-bank-account-ready': stripe_account_ready
  .row.bank-routing-2.hidden
    .col-12
      = form.label :bank_routing_2, t("stripe_accounts.form_bank.bank_routing_2")+"*"
      = form.text_field :bank_routing_2, class: 'required', country_regexp: 'routing_2',
        'stripe-bank-account-ready': stripe_account_ready
  .row.bank-routing-number.hidden
    .col-12
      = form.label :bank_routing_number, t("stripe_accounts.form_bank.bank_routing_number")+"*"
      = form.text_field :bank_routing_number, class: 'required', country_regexp: 'routing_number',
        'stripe-bank-account-ready': stripe_account_ready
  .row.bank-account-number.country-dependent{"data-country-except" => "NZ"}
    .col-12
      = form.label :bank_account_number, t("stripe_accounts.form_bank.bank_account_number")+"*"
      = form.text_field :bank_account_number, class: 'required',
        value: presenter.stripe_seller_account[:bank_number_info] || form.object.bank_account_number,
        country_regexp: 'account_number',
        'stripe-bank-account-ready': stripe_account_ready
  .row.bank-account-number.country-dependent{"data-country-only" => "NZ"}
    .col-12
      = form.label :bank_account_number_common, t("stripe_accounts.form_bank.bank_account_number")+"*"
      = form.text_field :bank_account_number_common, class: 'required',
        value: presenter.stripe_seller_account[:bank_number_info] || form.object.bank_account_number_common,
        country_regexp: 'account_number',
        'stripe-bank-account-ready': stripe_account_ready
  - if stripe_account_ready
    .row
      .col-12
        = label_tag :update_also_bank_account do
          = check_box_tag :update_also_bank_account, 1, false
          = t("stripe_accounts.form_bank.update_also_bank_account")
- content_for :extra_javascript do
  :javascript
    window.ST.stripe_form_i18n = #{I18n.t("stripe_accounts.form_bank.messages").to_json.html_safe};

app/views/payment_settings/_personal_id_number.haml
= fields_for presenter.stripe_account_form do |form|
  .row.country-dependent{"data-country-only" => "US,PR"}
    .col-12
      = label_tag :ssn_last_4, t("stripe_accounts.form_pin.ssn_last_4")+"*"
      = form.text_field :ssn_last_4, placeholder: '1234', required: true
  .row.country-dependent{"data-country-only" => "HK"}
    .col-12
      = label_tag :id_number, t("stripe_accounts.form_pin.hong_kong_identity_card")+"*"
      = form.text_field :id_number, placeholder: 'XY123456', required: true
  .row.country-dependent{"data-country-only" => "SG"}
    .col-12
      = label_tag :id_number, t("stripe_accounts.form_pin.singapore_identity_card")+"*"
      = form.text_field :id_number, placeholder: 'X1234567Y', required: true

app/views/payment_settings/_stripe_name.haml
= fields_for presenter.stripe_account_form do |form|
  - if presenter.stripe_account_ready
    = form.date_select :birth_date, { discard_day: true, discard_month: true, discard_year: true }
  .row
    .col-12
      = form.error_messages

  - name_class = presenter.stripe_seller_account[:address_country] == 'JP' ? 'hidden' : ''
  #stripe-europe-name{class: name_class, "data-country-except" => 'JP'}
    .row
      .col-6
        = form.label :first_name, t("stripe_accounts.form_new.first_name")+"*"
        = form.text_field :first_name, class: 'required'
      .col-6
        = form.label :last_name, t("stripe_accounts.form_new.last_name")+"*"
        = form.text_field :last_name, class: 'required'

  - name_jp_class = "#{presenter.stripe_account_ready ? '' : 'country-dependent'}"
  - if (presenter.stripe_account_ready && presenter.stripe_seller_account[:address_country] == 'JP') || !presenter.stripe_account_ready
    %div{class: name_jp_class, "data-country-only" => 'JP'}
      .row
        .col-6
          = form.label :first_name_kana, t("stripe_accounts.form_new.first_name_kana")+"*"
          = form.text_field :first_name_kana, class: 'required'
        .col-6
          = form.label :last_name_kana, t("stripe_accounts.form_new.last_name_kana")+"*"
          = form.text_field :last_name_kana, class: 'required'
      .row
        .col-6
          = form.label :first_name_kanji, t("stripe_accounts.form_new.first_name_kanji")+"*"
          = form.text_field :first_name_kanji, class: 'required'
        .col-6
          = form.label :last_name_kanji, t("stripe_accounts.form_new.last_name_kanji")+"*"
          = form.text_field :last_name_kanji, class: 'required'
      .row
        .col-12
          = form.label :gender, t("stripe_accounts.form_new.gender")+"*"
          - choices = [[t("stripe_accounts.form_new.male"), 'male'], [t("stripe_accounts.form_new.female"), 'female']]
          = form.select :gender, choices, { include_blank: true }, class: 'required'

  = form.hidden_field :email
  = form.hidden_field :url

  - unless presenter.stripe_account_ready
    .row
      .col-12
        = form.label :birth_date, t("stripe_accounts.form_new.birth_date")+"*"
        = form.date_select :birth_date, {:start_year => Date.current.year-18, :end_year => 1920, order: [:day, :month, :year], :use_month_names => I18n.t("datepicker.months").values}, class: 'required'

  .row
    .col-12
      - if presenter.stripe_account_ready
        = label_tag t("stripe_accounts.form_new.country")
        = CountryI18nHelper.translate_country(presenter.stripe_seller_account[:address_country])
        = form.hidden_field :address_country, value: presenter.stripe_seller_account[:address_country]
      - else
        = form.label :address_country, t("stripe_accounts.form_new.address_country")+"*"
        = form.select :address_country, presenter.stripe_available_countries, {prompt: t("stripe_accounts.form_new.select_country")}, {style: "min-width: 200px"}

app/views/payment_settings/_stripe_wizard.haml
= javascript_include_tag "#{STRIPE_JS_HOST}/v3/"
- if presenter.stripe_account_ready
  - if presenter.stripe_bank_account_ready
    .row
      .col-12
        - if presenter.stripe_account_verified?
          %h3.paypal-account-connected
            =icon_tag("check", ["icon-fix"])
            =t("stripe_accounts.stripe_bank_connected")
          %p
            =t("stripe_accounts.stripe_can_accept")
        - elsif presenter.stripe_account_restricted?
          %h3.paypal-account-disabled
            =icon_tag("cross", ["icon-fix"])
            =t("stripe_accounts.stripe_account_restricted")
          %p
            =t("stripe_accounts.stripe_account_restricted_info")
        - elsif presenter.stripe_account_restricted_soon?
          %h3.stripe-account-restricted-soon
            =icon_tag("minus", ["icon-fix"])
            =t("stripe_accounts.stripe_account_restricted_soon")
          %p
            =t("stripe_accounts.stripe_account_restricted_soon_info")
        - elsif presenter.stripe_account_pending_verification?
          %h3.stripe-account-pending-verification
            =icon_tag("check", ["icon-fix"])
            =t("stripe_accounts.stripe_account_pending_verification")
          %p
            =t("stripe_accounts.stripe_account_pending_verification_info")

    .row
      = link_to t("stripe_accounts.form_new.edit"), "#", id: "edit-stripe-info"
  - elsif !presenter.paypal_enabled
    .row
      .col-12
        %h3= t("payment_settings.credit_card")
        %p
          = t("payment_settings.credit_card_bank_details")
        %p
          = link_to t("payment_settings.add_bank_details"), '#', id: "edit-stripe-info"


  %div.hidden#stripe_forms
    .row.paypal-wizard.connect-row
      .col-12
        .paypal-wizard-content.connect-row
          = form_tag update_person_payment_settings_path(@current_user),
            id: "stripe-account-form", multipart: true, method: :put do
            = render 'stripe_name', presenter: presenter
            = render 'address_fields_form', presenter: presenter
            = render 'bank_fields_form', presenter: presenter
            = render 'verification_fields_form', presenter: presenter

            .col-4
              = link_to t('stripe_accounts.form_new.cancel'), person_payment_settings_path(@current_user), style: 'float: right; margin-top: 1.5em'
              = button_tag t('stripe_accounts.form_new.save_details')
  - content_for :extra_javascript do
    :javascript
      $(function(){ 
      $("#edit-stripe-info").click(function(){
        $("#stripe_forms").toggleClass("hidden");
        $("#edit-stripe-info").hide();
        return false;
      });
      if(#{presenter.stripe_account[:stripe_bank_id].blank? || flash[:error].present?}) {
        $("#edit-stripe-info").hide();
        $("#stripe_forms").toggleClass("hidden");
      }})
- else
  %p
    = t("stripe_accounts.form_new.need_info")
  .row.paypal-wizard.connect-row
    %div
      .paypal-wizard-content.connect-row
        .col-12
          = form_tag create_person_payment_settings_path(@current_user), id: "stripe-account-form", multipart: true do
            = render 'stripe_name', presenter: presenter
            .country-dependent{"data-country-except" => "XXX"}
              = render 'address_fields_form', presenter: presenter
            .country-dependent{"data-country-except" => "XXX"}
              = render 'bank_fields_form', presenter: presenter
            = render 'personal_id_number', presenter: presenter
            = render 'verification_fields_form', presenter: presenter

            .country-dependent{"data-country-except" => "XXX"}
              - base_terms_url = "https://stripe.com/COUNTRY/connect-account/legal#translation"
              - stripe_link = link_to t("stripe_accounts.form_new.tos_link_title"), base_terms_url, target: "_blank", data: {terms_url: base_terms_url}, id: "stripe-terms-link"
              = t("stripe_accounts.form_new.tos_link", stripe_link: stripe_link ).html_safe

              = button_tag t('stripe_accounts.form_new.save_details')

- stripe_data = stripe_default_data2.dup
- stripe_data = stripe_data.merge(update: true) if presenter.stripe_account_ready
- content_for :extra_javascript do
  :javascript
    $(function() {
      window.ST.StripeBankForm.init(#{stripe_data.to_json.html_safe});
    });

app/views/payment_settings/_verification_fields_form.haml
- if presenter.seller_needs_verification
  %h3
    = t("stripe_accounts.form_verification.need_verification")

  - id_number_field = :id_number
  = fields_for :stripe_account_form do |form|
    .row.country-dependent{"data-country-only" => "CA"}
      .col-12
        = label_tag id_number_field, t("stripe_accounts.form_pin.social_insurance_number")+"*"
        = form.text_field id_number_field, placeholder: '123456789', 'ca-social-insurance-number': true,
          data: {'msg-ca-social-insurance-number': t('stripe_accounts.form_pin.messages.social_insurance_number')}
    .row.country-dependent{"data-country-only" => "US,PR"}
      .col-12
        = label_tag id_number_field, t("stripe_accounts.form_pin.social_security_number")+"*"
        = form.text_field id_number_field, placeholder: '123456789', required: true
    .row
      .col-12
        = label_tag :document, t("stripe_accounts.form_verification.document")
        = form.file_field :document, required: true